# SPDX-FileCopyrightText: 2011-2026 Blender Foundation
#
# SPDX-License-Identifier: Apache-2.0

# Development installation of Cycles.
#
# When `WITH_CYCLES_DEVELOPMENT_INSTALL` is enabled, this installs Cycles as a
# library that external projects can link against:
#
#   - the Cycles headers, installed under `<prefix>/include/cycles`
#   - a single combined shared library `<prefix>/lib/libcycles.so` that bundles
#     every Cycles module plus the precompiled dependencies it needs
#   - a CMake package (`find_package(Cycles)`) exporting the `Cycles::cycles`
#     imported target, with the include directories and compile definitions
#     required to compile against the Cycles headers.
#
# The combined shared library is used instead of the individual static archives
# so that consumers do not have to reproduce Cycles' internal link order and
# dependency list.

if(WITH_BLENDER)
  message(FATAL_ERROR "WITH_CYCLES_DEVELOPMENT_INSTALL is only supported for the standalone Cycles repository")
endif()

if(NOT CYCLES_STANDALONE_REPOSITORY)
  message(FATAL_ERROR "WITH_CYCLES_DEVELOPMENT_INSTALL is only supported for the standalone Cycles repository")
endif()

set(DEVELOPMENT_INSTALL_INCLUDE_DIR "${CMAKE_INSTALL_PREFIX}/include/cycles")
set(DEVELOPMENT_INSTALL_LIB_DIR "${CMAKE_INSTALL_PREFIX}/${PLATFORM_LIB_INSTALL_DIR}")
set(DEVELOPMENT_INSTALL_CMAKE_DIR "${DEVELOPMENT_INSTALL_LIB_DIR}/cmake/Cycles")

# ---------------------------------------------------------------------------
# Version.

file(READ "${PROJECT_SOURCE_DIR}/src/util/version.h" _cycles_version_header)
string(REGEX MATCH "CYCLES_VERSION_MAJOR +([0-9]+)" _ "${_cycles_version_header}")
set(CYCLES_VERSION_MAJOR "${CMAKE_MATCH_1}")
string(REGEX MATCH "CYCLES_VERSION_MINOR +([0-9]+)" _ "${_cycles_version_header}")
set(CYCLES_VERSION_MINOR "${CMAKE_MATCH_1}")
string(REGEX MATCH "CYCLES_VERSION_PATCH +([0-9]+)" _ "${_cycles_version_header}")
set(CYCLES_VERSION_PATCH "${CMAKE_MATCH_1}")
set(CYCLES_VERSION_STRING "${CYCLES_VERSION_MAJOR}.${CYCLES_VERSION_MINOR}.${CYCLES_VERSION_PATCH}")

# ---------------------------------------------------------------------------
# Combined shared library.

set(CYCLES_DEVELOPMENT_TARGETS
  cycles_util
  cycles_graph
  cycles_bvh
  cycles_subd
  cycles_device
  cycles_scene
  cycles_session
  cycles_integrator
  cycles_kernel_cpu
)
if(WITH_CYCLES_OSL)
  list(APPEND CYCLES_DEVELOPMENT_TARGETS cycles_kernel_osl)
endif()

set(_cycles_whole_archive_targets)
foreach(_target IN LISTS CYCLES_DEVELOPMENT_TARGETS)
  list(APPEND _cycles_whole_archive_targets "$<TARGET_FILE:${_target}>")
endforeach()

# External dependencies are part of the public link interface: Cycles headers
# reference them (TBB, OpenImageIO, ...), so consumers need to compile and link
# against them as well.
set(_cycles_public_libraries)
cycles_external_libraries_append(_cycles_public_libraries)
if(TARGET extern_sky)
  list(APPEND _cycles_public_libraries extern_sky)
endif()

# Used below when scanning the link interface for the generated CMake package.
set(_cycles_shared_libraries ${CYCLES_DEVELOPMENT_TARGETS} ${_cycles_public_libraries})

# CMake requires a library target to have at least one source of its own. All
# the real code is pulled in from the module archives below, so a tiny
# generated translation unit is used to satisfy that requirement.
set(_cycles_shared_source "${PROJECT_BINARY_DIR}/cycles_shared.cpp")
file(GENERATE OUTPUT "${_cycles_shared_source}"
  CONTENT "// Generated by Cycles. Gives the combined library a translation unit.\nnamespace ccl {\nvoid cycles_shared_translation_unit() {}\n}\n")

add_library(cycles_shared SHARED "${_cycles_shared_source}")
set_target_properties(cycles_shared PROPERTIES
  OUTPUT_NAME cycles
  VERSION "${CYCLES_VERSION_STRING}"
  SOVERSION "${CYCLES_VERSION_MAJOR}"
  POSITION_INDEPENDENT_CODE ON
  INSTALL_RPATH "$ORIGIN"
)

if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
  target_link_libraries(cycles_shared PRIVATE
    "-Wl,--whole-archive"
    ${_cycles_whole_archive_targets}
    "-Wl,--no-whole-archive"
    # Linking the module targets after the whole-archive group pulls in their
    # transitive dependencies (TBB, zstd, ...) so they are resolved into the
    # combined library and available to consumers.
    ${CYCLES_DEVELOPMENT_TARGETS}
  )
else()
  target_link_libraries(cycles_shared PRIVATE
    ${CYCLES_DEVELOPMENT_TARGETS}
  )
endif()

target_link_libraries(cycles_shared PUBLIC ${_cycles_public_libraries})

# The module archives are linked via $<TARGET_FILE:...> (so they can be wrapped
# in --whole-archive), which does not create a build-order dependency. Make sure
# they are built before the combined library is linked.
add_dependencies(cycles_shared ${CYCLES_DEVELOPMENT_TARGETS})

# In-tree consumers (for example a superbuild that pulls Cycles in with
# add_subdirectory or FetchContent) link this target directly and therefore
# need the include directories and compile definitions Cycles itself compiles
# with. The generated CMake package carries the equivalent information for
# out-of-tree consumers.
set(_cycles_interface_include_dirs
  "${PROJECT_SOURCE_DIR}/src"
  "${PROJECT_SOURCE_DIR}/third_party/atomic"
  "${PROJECT_SOURCE_DIR}/third_party/cuew/include"
  "${PROJECT_SOURCE_DIR}/third_party/hipew/include"
  "${PROJECT_SOURCE_DIR}/third_party/sky/include"
  "${PROJECT_SOURCE_DIR}/third_party/mikktspace"
  ${CYCLES_EXPORT_INCLUDE_DIRS}
)
list(REMOVE_DUPLICATES _cycles_interface_include_dirs)

set(_cycles_interface_compile_definitions)
foreach(_def IN LISTS CYCLES_EXPORT_COMPILE_DEFINITIONS)
  if(_def MATCHES "[<>]")
    continue()
  endif()
  if(_def MATCHES "^(DEBUG|NDEBUG)$")
    continue()
  endif()
  list(APPEND _cycles_interface_compile_definitions "${_def}")
endforeach()
list(REMOVE_DUPLICATES _cycles_interface_compile_definitions)

target_include_directories(cycles_shared INTERFACE ${_cycles_interface_include_dirs})
target_compile_definitions(cycles_shared INTERFACE ${_cycles_interface_compile_definitions})
target_compile_features(cycles_shared INTERFACE cxx_std_20)
add_library(Cycles::cycles ALIAS cycles_shared)

# ---------------------------------------------------------------------------
# Headers.

install(DIRECTORY "${PROJECT_SOURCE_DIR}/src/"
  DESTINATION "${DEVELOPMENT_INSTALL_INCLUDE_DIR}"
  FILES_MATCHING
  PATTERN "*.h"
  PATTERN "*.cuh"
)

# Third party headers included by Cycles headers.
install(DIRECTORY "${PROJECT_SOURCE_DIR}/third_party/atomic/"
  DESTINATION "${DEVELOPMENT_INSTALL_INCLUDE_DIR}/third_party/atomic"
  FILES_MATCHING PATTERN "*.h"
)
foreach(_third_party cuew hipew sky)
  if(EXISTS "${PROJECT_SOURCE_DIR}/third_party/${_third_party}/include")
    install(DIRECTORY "${PROJECT_SOURCE_DIR}/third_party/${_third_party}/include/"
      DESTINATION "${DEVELOPMENT_INSTALL_INCLUDE_DIR}/third_party/${_third_party}"
      FILES_MATCHING PATTERN "*.h"
    )
  endif()
endforeach()
if(EXISTS "${PROJECT_SOURCE_DIR}/third_party/mikktspace")
  install(DIRECTORY "${PROJECT_SOURCE_DIR}/third_party/mikktspace/"
    DESTINATION "${DEVELOPMENT_INSTALL_INCLUDE_DIR}/third_party/mikktspace"
    FILES_MATCHING PATTERN "*.h"
  )
endif()

# Some precompiled dependencies are not part of the regular bundled library set
# but are still needed at runtime by the combined shared library. In particular
# the oneAPI/SYCL runtime is pulled in transitively (e.g. through OpenSubdiv)
# even when the oneAPI device is disabled.
if(DEFINED _cycles_lib_dir AND EXISTS "${_cycles_lib_dir}/dpcpp/lib")
  file(GLOB _cycles_extra_runtime_libs "${_cycles_lib_dir}/dpcpp/lib/*.so*")
  if(_cycles_extra_runtime_libs)
    install(FILES ${_cycles_extra_runtime_libs}
      DESTINATION "${DEVELOPMENT_INSTALL_LIB_DIR}"
    )
  endif()
endif()

# ---------------------------------------------------------------------------
# CMake package configuration.

# Include directories needed to compile against the Cycles headers: the
# installed Cycles headers plus the external precompiled dependency headers.
set(_cycles_config_include_dirs
  "${DEVELOPMENT_INSTALL_INCLUDE_DIR}"
  "${DEVELOPMENT_INSTALL_INCLUDE_DIR}/third_party/atomic"
  "${DEVELOPMENT_INSTALL_INCLUDE_DIR}/third_party/cuew"
  "${DEVELOPMENT_INSTALL_INCLUDE_DIR}/third_party/hipew"
  "${DEVELOPMENT_INSTALL_INCLUDE_DIR}/third_party/sky"
  "${DEVELOPMENT_INSTALL_INCLUDE_DIR}/third_party/mikktspace"
)

# External dependency includes are carried by imported/interface targets rather
# than by directory-level include directories, so collect them by walking the
# link interface of everything the combined shared library links against.
set(_cycles_scanned_targets)
set(_cycles_config_library_files)
macro(_cycles_scan_target target)
  if(TARGET "${target}" AND NOT "${target}" IN_LIST _cycles_scanned_targets)
    list(APPEND _cycles_scanned_targets "${target}")

    get_target_property(_scanned_includes "${target}" INTERFACE_INCLUDE_DIRECTORIES)
    if(_scanned_includes)
      foreach(_dir IN LISTS _scanned_includes)
        if(IS_ABSOLUTE "${_dir}" AND EXISTS "${_dir}")
          list(APPEND _cycles_config_include_dirs "${_dir}")
        endif()
      endforeach()
    endif()

    foreach(_prop IMPORTED_LOCATION IMPORTED_LOCATION_RELEASE IMPORTED_LOCATION_NOCONFIG)
      get_target_property(_scanned_location "${target}" ${_prop})
      if(_scanned_location AND NOT _scanned_location MATCHES "-NOTFOUND$")
        list(APPEND _cycles_config_library_files "${_scanned_location}")
      endif()
      unset(_scanned_location)
    endforeach()

    get_target_property(_scanned_links "${target}" INTERFACE_LINK_LIBRARIES)
    if(_scanned_links)
      foreach(_link IN LISTS _scanned_links)
        if(TARGET "${_link}")
          _cycles_scan_target("${_link}")
        elseif(IS_ABSOLUTE "${_link}" AND EXISTS "${_link}")
          list(APPEND _cycles_config_library_files "${_link}")
        endif()
      endforeach()
    endif()
  endif()
endmacro()

foreach(_target IN LISTS _cycles_shared_libraries)
  _cycles_scan_target("${_target}")
endforeach()

foreach(_dir IN LISTS CYCLES_EXPORT_INCLUDE_DIRS)
  if(NOT IS_ABSOLUTE "${_dir}" OR NOT EXISTS "${_dir}")
    continue()
  endif()
  if(_dir MATCHES "^\\$<" OR _dir MATCHES "^${PROJECT_SOURCE_DIR}" OR _dir MATCHES "^${PROJECT_BINARY_DIR}")
    continue()
  endif()
  list(APPEND _cycles_config_include_dirs "${_dir}")
endforeach()
list(REMOVE_DUPLICATES _cycles_config_include_dirs)

set(_cycles_config_include_code "set(Cycles_INCLUDE_DIRS\n")
foreach(_dir IN LISTS _cycles_config_include_dirs)
  string(APPEND _cycles_config_include_code "  \"${_dir}\"\n")
endforeach()
string(APPEND _cycles_config_include_code ")\n")

# Compile definitions that affect the contents of Cycles headers.
set(_cycles_config_definitions)
foreach(_def IN LISTS CYCLES_EXPORT_COMPILE_DEFINITIONS)
  if(_def MATCHES "[<>]")
    continue()
  endif()
  if(_def MATCHES "^(DEBUG|NDEBUG)$")
    continue()
  endif()
  list(APPEND _cycles_config_definitions "${_def}")
endforeach()
list(REMOVE_DUPLICATES _cycles_config_definitions)

set(_cycles_config_definition_code "set(Cycles_COMPILE_DEFINITIONS\n")
foreach(_def IN LISTS _cycles_config_definitions)
  string(REPLACE "\\" "\\\\" _def "${_def}")
  string(REPLACE "\"" "\\\"" _def "${_def}")
  string(APPEND _cycles_config_definition_code "  \"${_def}\"\n")
endforeach()
string(APPEND _cycles_config_definition_code ")\n")

set(CYCLES_INCLUDE_DIRS_CODE "${_cycles_config_include_code}")
set(CYCLES_COMPILE_DEFINITIONS_CODE "${_cycles_config_definition_code}")

# External libraries the combined shared library was linked against. Consumers
# that use inline Cycles headers (TBB parallel loops, etc.) need these on their
# own link line, since transitive NEEDED entries are not used for symbol
# resolution by default.
set(_cycles_config_dependency_libs)
set(_cycles_interface_link_libraries)
foreach(_lib IN LISTS _cycles_config_library_files)
  if(NOT IS_ABSOLUTE "${_lib}" OR NOT EXISTS "${_lib}")
    continue()
  endif()
  if(DEFINED _cycles_lib_dir AND NOT _lib MATCHES "^${_cycles_lib_dir}")
    continue()
  endif()
  # Only shared libraries need to be added to the consumer link line. Static
  # libraries are already linked into the combined shared library and their
  # symbols are exported from it.
  if(NOT _lib MATCHES "\\.(so|dylib|dll)($|\\.)")
    continue()
  endif()
  get_filename_component(_lib_name "${_lib}" NAME)
  list(APPEND _cycles_config_dependency_libs "${_lib_name}")
  # In-tree consumers link against the build-tree locations directly.
  list(APPEND _cycles_interface_link_libraries "${_lib}")
endforeach()
list(REMOVE_DUPLICATES _cycles_config_dependency_libs)
list(REMOVE_DUPLICATES _cycles_interface_link_libraries)

# Some precompiled dependencies are needed on consumer link lines but are not
# part of the combined library's transitive interface (for example the SYCL
# runtime required by the precompiled Embree build). Expose them so in-tree
# consumers resolve all symbols.
if(_cycles_interface_link_libraries)
  target_link_libraries(cycles_shared INTERFACE ${_cycles_interface_link_libraries})
endif()

# Precompiled shared libraries live in per-package directories and some of them
# (for example OpenEXR, which needs libopenjph) use RUNPATH="$ORIGIN", so their
# own dependencies are not found through the consuming binary's rpath. Expose
# the bundled library directories so an in-tree consumer can set a runtime
# library search path, mirroring PLATFORM_ENV_BUILD used by the standalone app.
set(CYCLES_BUNDLED_LIBRARY_DIRS "${PLATFORM_BUNDLED_LIBRARY_DIRS}" CACHE INTERNAL
    "Directories containing the precompiled shared libraries Cycles bundles")

set(_cycles_config_dependency_code "set(Cycles_DEPENDENCY_LIBRARIES\n")
foreach(_lib_name IN LISTS _cycles_config_dependency_libs)
  string(APPEND _cycles_config_dependency_code "  \"\${Cycles_LIBRARY_DIR}/${_lib_name}\"\n")
endforeach()
string(APPEND _cycles_config_dependency_code ")\n")
set(CYCLES_DEPENDENCY_LIBRARIES_CODE "${_cycles_config_dependency_code}")

include(CMakePackageConfigHelpers)

configure_package_config_file(
  "${PROJECT_SOURCE_DIR}/src/cmake/CyclesConfig.cmake.in"
  "${PROJECT_BINARY_DIR}/CyclesConfig.cmake"
  INSTALL_DESTINATION "${DEVELOPMENT_INSTALL_CMAKE_DIR}"
)

write_basic_package_version_file(
  "${PROJECT_BINARY_DIR}/CyclesConfigVersion.cmake"
  VERSION "${CYCLES_VERSION_STRING}"
  COMPATIBILITY SameMajorVersion
)

install(TARGETS cycles_shared
  LIBRARY DESTINATION "${DEVELOPMENT_INSTALL_LIB_DIR}"
  ARCHIVE DESTINATION "${DEVELOPMENT_INSTALL_LIB_DIR}"
  RUNTIME DESTINATION "${DEVELOPMENT_INSTALL_LIB_DIR}"
)

install(FILES
  "${PROJECT_BINARY_DIR}/CyclesConfig.cmake"
  "${PROJECT_BINARY_DIR}/CyclesConfigVersion.cmake"
  DESTINATION "${DEVELOPMENT_INSTALL_CMAKE_DIR}"
)
